### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Storm-23** [ashsvis/VectorGraphicsEditor#1]
- https://github.com/ashsvis/VectorGraphicsEditor/blob/5f8a2088d601d9739529afa6b29b06b9d665995d/SimpleEditor/SelectionController.cs#L84

if (Selection.Count == 0)
    return;

- https://github.com/ashsvis/VectorGraphicsEditor/blob/5f8a2088d601d9739529afa6b29b06b9d665995d/EditorModel/Figures/Marker.cs#L17
AllowedOperations.All ^ (AllowedOperations.Size | AllowedOperations.Rotate | AllowedOperations.Select)

А вообще лучше это вынести в FigureBuilder.

- https://github.com/ashsvis/VectorGraphicsEditor/blob/5f8a2088d601d9739529afa6b29b06b9d665995d/EditorModel/Figures/Renderer.cs#L14
Уберите из конструктора Figure.
У разных фигур может быть один и тот же рендерер. Поэтому фигуру для рендеринга нужно передавать в метод Render.

- https://github.com/ashsvis/VectorGraphicsEditor/blob/5f8a2088d601d9739529afa6b29b06b9d665995d/SimpleEditor/FormSimpleEditor.cs#L55
_modifers - не нужно, вместо этого:

_selectionController.OnMouseDown(e.Location, ModifierKeys);

**Comment by Storm-23** [comment]
И еще в этих методах
https://github.com/ashsvis/VectorGraphicsEditor/blob/5f8a2088d601d9739529afa6b29b06b9d665995d/SimpleEditor/FormSimpleEditor.cs#L53-L57
Нужно проверять, что нажата именно левая кнопка мыши.

**Comment by ashsvis** [comment]
Ok, Внесено.
