### ISSUE TITLE
Skew

### ISSUE THREAD

**Issue by Storm-23** [ashsvis/VectorGraphicsEditor#10]
Искажения работают отлично.
Но:
1) Давайте сделаем skew более стандартным - с четырмя маркерами (как в фотошопе например):
![1](https://user-images.githubusercontent.com/38248176/48981106-07406e80-f0da-11e8-9433-7aab2d2a93ff.png)

2) Зачем вот это:

```
    public enum SelectedMode
    {
        Default,
        Skew,
        Verticies
    }
```
?
Не нужно плодить сущности без надобности.  У нас же уже есть enum для режима - EditorMode. Вот там и должно быть Skew и Verticies.

3) Интерфейс лучше делать на английском языке.
И не писать длиннющие фразы типа "Режим Искажений", пиши просто "Skew",  "Edit Verticies", "Selection"

**Comment by ashsvis** [comment]
Хорошо, я займусь этим.

**Comment by ashsvis** [comment]
Сделал.
