### ISSUE TITLE
Polyline

### ISSUE THREAD

**Issue by Lexeq** [ashsvis/VectorGraphicsEditor#16]
Если все сегменты PolyLine находятся на одной прямой, то канва крашится. Происходит это из-за того, что прямоугольник, ограничивающий фигуру имеет нулевой размер, из-за этого дальше происходит деление на ноль, точки получают координату NaN, контрол не может это отрисовать и падает.
Всё начинается отсюда https://github.com/ashsvis/VectorGraphicsEditor/blob/909421e3ca5aa2531527defb762abd6eacf8c945/EditorModel/Figures/FigureBuilder.cs#L200-L201
я не понял что там за 0,5 и в зависимости от этого там либо скобки поставить либо проверять ширину/высоту на 0.

**Comment by ashsvis** [comment]
Спасибо за Вашу бдительность!
Этот случай был мне известен, а теперь, благодаря Вам, нашлось время исправить. 
Смещение -0.5 задаётся каждой точке, так как согласно модели, начальная точка фигуры находится по её центру (так задумано Storm23 и подробности, почему это так, нужно спрашивать у него).
