### ISSUE TITLE
Строим интерфейс вокруг модели

### ISSUE THREAD

**Issue by Storm-23** [ashsvis/VectorGraphicsEditor#2]
`Встраивание модели в интерфейс, день 2`

Вот принципиально неправильный подход.
Не модель встраивается в интерфейс. А интерфейс строится вокруг модели.
Ядро системы - это модель. Она одна и она выполняет основной функционал приложения. Интерфейс - это просто визуальная обвязка модели, которая позволяет пользователю взаимодействовать с моделью. 
К тому же интерфейсов может быть много.

**Comment by ashsvis** [comment]
Ok
