### ISSUE TITLE
SelectedFigureChanged 

### ISSUE THREAD

**Issue by Storm-23** [ashsvis/VectorGraphicsEditor#3]
https://github.com/ashsvis/VectorGraphicsEditor/blob/57d6810433189e78b0a8cfaf436d08f55cf907f8/SimpleEditor/SelectionController.cs#L282

Событие SelectedFigureChanged - вызывается при изменении набора выделенных фигур. То есть оно возникает, когда мы выделяем или снимаем выделение с фигуры.

Для операций же изменения  геометрии (то есть тягания маркеров) - нужно сделать другое событие. Назвать его например SelectedTransformChanging. При окончании перетягивания - SelectedTransformChanged.

**Comment by ashsvis** [comment]
Ok
