### ISSUE TITLE
По командам

### ISSUE THREAD

**Issue by Storm-23** [ashsvis/VectorGraphicsEditor#8]
Предлагаю сделать простую команду, которая будет сериализовать слой целиком и десериализовать обратно.
Однако имя команды путь задается разное, в зависимости от той операции перед которой команда была создана. 
То есть, если мы создаем фигуру, то имя команды должно быть Создание Фигуры. Если мы меняем размеры - Изменение Размеров и т.д.
Это позволит сделать список именованых команд в кнопке Undo.

**Comment by ashsvis** [comment]
Согласен.

**Comment by Storm-23** [comment]
Зачем Undo/Redo в SelectionController?
```
        private void CreateFigure(Point point)
        {
            //создаем новую фигуру
            var newFig = CreateFigureRequest();
            newFig.Transform.Matrix.Translate(point.X + 0.5f, point.Y + 0.5f);
            _undoRedoManager.Execute(new LayerChangingCommand(_layer, "CreateFigure"));// <------- !!!!
            _layer.Figures.Add(newFig);
            _selection.Add(newFig);
            CreateFigureRequest = null;
            OnSelectedFigureChanged();
        }
```

Основная цель хорошей архитектуры - разделение программы на независимые части. Зачем же пихать undo/redo в класс, который занимается выделением фигур ?? Это не его обязанность делать undo/redo.
Это должна делать главная форма в методах обработки команд меню, или в обработчиках событий SelectionController. Но этого точно не должно быть внутри SelectionController.

**Comment by ashsvis** [comment]
Да, но эту команду нужно вызывать ДО изменений в слое, Придётся теперь городить события...

**Comment by ashsvis** [comment]
Перенёс в интерфейс. Undo работает, а Redo нет. Не подскажете, почему?

**Comment by ashsvis** [comment]
Большое спасибо за Undo/Redo. Сделал Flip и Rotate. Посмотрите пожалуйста, чтобы двигаться дальше.
